# -*- coding: utf-8 -*-
"""XGBoost_Regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9N6SG9H1RjWSGos9Yh5mwaiP5prRJJ7
"""

#Installing XGBoost
!pip install xgboost

#importing library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor

#Uploading the data
from google.colab import files
uploaded = files.upload()

#getting the data into a dataframe
df = pd.read_csv('boston.csv')

df.head()

# Separating training and testing data
X = df.drop('MEDV', axis =1)
y = df['MEDV']

# Performing train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

#Fitting the model
model = XGBRegressor()
model.fit(X_train, y_train)

#Taking prediction from the data
y_pred = model.predict(X_test)

#Evaluating the model
from sklearn import metrics
print('R2 Score :', np.round(metrics.r2_score(y_test, y_pred),2))
print('RMSE :', np.round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),2))